### ISSUE TITLE
When i train the train_f0_vq.py , I meet a trouble . 

### ISSUE THREAD

**Issue by GitYesm** [facebookresearch/speech-resynthesis#16]
Epoch: 1
Traceback (most recent call last):
  File "train_f0_vq.py", line 217, in <module>
    main()
  File "train_f0_vq.py", line 213, in main
    train(a.local_rank, a, h)
  File "train_f0_vq.py", line 101, in train
    for i, batch in enumerate(train_loader):
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
soundfile.LibsndfileError: <exception str() failed>
Killing subprocess 2908
Traceback (most recent call last):
  File "/root/miniconda3/envs/test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/test/bin/python', '-u', 'train_f0_vq.py', '--local_rank=0', '--checkpoint_path', 'checkpoints/lj_f0_vq', '--config', 'configs/LJSpeech/f0_vqvae.json']' returned non-zero exit status 1.

**Comment by GitYesm** [comment]
I search some data ,pip install soundfile==0.10.3.post1 solve this question .  But another problem arises ： 
checkpoints directory :  checkpoints/lj_f0_vq
Epoch: 1
Traceback (most recent call last):
  File "train_f0_vq.py", line 217, in <module>
    main()
  File "train_f0_vq.py", line 213, in main
    train(a.local_rank, a, h)
  File "train_f0_vq.py", line 101, in train
    for i, batch in enumerate(train_loader):
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/speech-pre/dataset.py", line 374, in __getitem__
    audio, sampling_rate = load_audio(filename)
  File "/root/autodl-tmp/speech-pre/dataset.py", line 71, in load_audio
    data, sampling_rate = sf.read(full_path, dtype='int16')
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/soundfile.py", line 256, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'data/LJSpeech-1.1/wavs_16khz/LJ026-0010.wav': System error.

Killing subprocess 4140
Traceback (most recent call last):
  File "/root/miniconda3/envs/test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/test/bin/python', '-u', 'train_f0_vq.py', '--local_rank=0', '--checkpoint_path', 'checkpoints/lj_f0_vq', '--config', 'configs/LJSpeech/f0_vqvae.json']' returned non-zero exit status 1.
